name: Update Version from Git Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag version
        id: extract_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Update version in PHP file
        run: |
          node update-version.js

      - name: Commit and push updated version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pkl-api-auth.php
          git commit -m "chore: update version to ${{ env.TAG_VERSION }}"
          git push origin HEAD:main