name: Update Version from Git Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag version
        id: extract_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Update version in PHP file
        run: |
          node update-version.js

      - name: Sync with remote and commit
        run: |
          git add pkl-api-auth.php
          git commit -m "temp: update version for ${{ env.TAG_VERSION }}"  # 📝 Commit ชั่วคราว
          git config --global pull.rebase true
          git pull origin main --rebase  # นำ Commit นี้ไป Rebase กับ Remote
          git push origin main